export const cieeCourses = [
  'Postura e Imagem Profissional',
  'Processo Seletivo',
  'LinkedIn: por que eu preciso?',
  'Preparatório para Concursos Públicos',
  'O Futuro do Mundo do Trabalho',
  'Microsoft Access 2010',
  'Microsoft Excel 2010',
  'Microsoft PowerPoint 2010',
  'Microsoft Word 2010',
  '7 Passos para Escolher sua Profissão',
  'Arte da Superação',
  'Seja empreendedor',
  'Desvendando o Consórcio na Prática',
  'Jovens em Tempos Digitais',
  'Ética e Liderança',
  'Sustentabilidade',
  'Conteúdos na Internet: Qual o melhor caminho?',
  'Soft Skills: As competências Sociais no presente',
  'Gestão das Emoções',
  'Gramática Prática',
  'Matemática I',
  'Matemática II',
  'Produção de Textos',
  'Técnicas da Expressão Verbal',
  'Cidadania Passo a Passo',
  'Libras - Língua Brasileira de Sinais',
  'Esse Direito é Meu',
  'Acordo Ortográfico da Língua Portuguesa de 1990',  
  'Coesão e Coerência Textual',
  'Concordância Verbal',
  'Internet das Coisas',
  'Inteligência Artificial',
  'Robótica',
  'Engenharia de Dados',
  'Computação em Nuvem',
  'Google Apresentações',
  'Google Documentos',
  'Google Planilhas',
  'Google Agenda',
  'Participação Feminina na Política',
  'Sistema Eleitoral Brasileiro',
  'Trajetória de Vida',
  'Os órgãos de Controle de Administração Pública',
  'E Agora? Como Escolher um Bom Candidato(A)?',
  'Estado, Democracia e Poderes',
  'O Mal que faz a Corrupção',
  'Os Partidos Políticos',
  'A Representação Político/Partidária',
  'A Menina Mulher Alcançado os Espaços de Poder e Decisão',
  'Empreendedorismo - Formando Jovens Empreendedores',
  'Empreendedorismo - Atitude Empreendedora',
  'Empreendedorismo - Formando Jovens Empreendedores II',
  'Empreendedorismo - Educação Financeira',
  'Ciclo de Palestras Pesquisador Empreendedor',
  'Como Investir em Você — ANBIMA',
  'Gestão de Finanças Pessoais — Banco Central do Brasil',
  'Introdução ao Mercado de Capitais — APIMEC/SP',
  'LIBRAS: Língua Brasileira de Sinais — USP',
  'Mercado Financeiro de A a Z — ANBIMA',
  'Cursos Diversos — Fundação Getúlio Vargas',
  'Google Ateliê Digital',
  'Escola Virtual Fundação Bradesco',
  'Intituto Êxito de Empreendedorismo',
  'C6 Bank',
  'Instituto Crescer',
  'Sicoob',
]