export const sebraeCourses = [
  'Marketing digital para o empreendedor',
  'Sua empresa nas redes sociais',
  'Os segredos por trás de um Instagram vendedor',
  'Como criar um site para sua empresa',
  'Como criar uma página no Facebook',
  'Como usar sites de busca para sua empresa',
  'Como anunciar em sites de vendas',
  'Como construir uma loja virtual',
  'Como fazer sua loja virtual em marketplace vender mais',
  'Como melhorar a gestão de sua loja virtual em marketplace',
  'O que é marketplace e como isso pode ajudar o seu negócio',
  'Estratégias de vendas para o comércio eletrônico',
  'Gestão estratégica para comércio eletrônico',
  'Logística para comércio eletrônico',
  'Marketing digital - módulo 1',
  'Marketing digital - módulo 2',
  'Marketing digital - módulo 3',
  'Marketing digital - módulo 4',
  'Como vender pela internet na crise do coronavírus',
  'Marketing digital: planejar para vender pela Internet',
  'Introdução à Indústria de Games',
  'Gestão financeira',
  'Aprender a empreender',
  'Atendimento ao cliente',
  'Gestão de pessoas',
  'Liderança: como desenvolver times de alta performance',
  'Iniciando um pequeno grande negócio',
  'Customer Success: como conquistar e manter clientes',
  'Gestão empresarial integrada',
  'Como vender mais e melhor',
  'Como planejar o seu negócio',
  'Planejamento estratégico para empreendedores'
]