export const technicaSenaclCourses = [
  'Técnico em Estética',
  'Técnico em Podologia',
  'Técnico em Massoterapia',
  'Especialização Técnica em Atendimento Podológico',
  'Técnico em Processos Fotográficos',
  'Técnico em Publicidade',
  'Técnico em Design de Interiores',
  'Técnico em Paisagismo',
  'Técnico em Design Gráfico',
  'Técnico em Teatro',
  'Técnico em Computação Gráfica',
  'Técnico em Multimídia',
  'Técnico em Processos Fotográficos',
  'Técnico em Nutrição e Dietética',
  'Técnico em Confeitaria',
  'Técnico em Gastronomia',
  'Técnico em Panificação',
  'Técnico em Recursos Humanos',
  'Técnico em Comércio Exterior',
  'Técnico em Administração',
  'Técnico em Logística',
  'Técnico em Finanças',
  'Técnico em Logística',
  'Técnico em Contabilidade',
  'Técnico em Paisagismo',
  'Segurança do Trabalho na Construção Civil',
  'Técnico em Meio Ambiente',
  'Técnico em Segurança do Trabalho',
  'Especialização Técnica em Higiene Ocupacional',
  'Meio Ambiente para Técnico em Segurança do Trabalho',
  'Técnico em Modelagem do Vestuário',
  'Técnico em Estilismo e Coordenação de Moda',
  'Técnico em Produção de Moda',
  'Especialização Técnica em Prótese sobre Implante',
  'Técnico em Nutrição e Dietética',
  'Especialização Técnica em Prótese Ortopédica Funcional',
  'Técnico em Hemoterapia',
  'Técnico em Análises Clínicas',
  'Técnico em Enfermagem',
  'Técnico em Farmácia',
  'Técnico em Óptica',
  'Técnico em Prótese Dentária',
  'Técnico em Radiologia',
  'Técnico em Saúde Bucal',
  'Técnico em Desenvolvimento de Sistemas',
  'Técnico em Segurança Cibernética',
  'Técnico em Internet das Coisas',
  'Técnico em Computação Gráfica',
  'Técnico em Informática',
  'Técnico em Informática para Internet',
  'Técnico em Manutenção e Suporte em Informática',
  'Técnico em Multimídia',
  'Técnico em Programação de Jogos Digitais',
  'Técnico em Redes de Computadores',
  'Guia Especializado em Atrativo Turístico Natural',
  'Técnico em Guia de Turismo',
  'Guia Especializado em Atrativo Turístico Cultural',
  'Técnico em Eventos',
  'Técnico em Hospedagem'
]

export const graduationSenacCourses = [
  'Administração',
  'Análise e Desenvolvimento de Sistemas',
  'Arquitetura e Urbanismo',
  'Audiovisual',
  'Ciência da Computação',
  'Ciências Contábeis',
  'Design',
  'Design de Animação',
  'Design de Moda',
  'Design Gráfico',
  'Enfermagem',
  'Engenharia de Computação',
  'Engenharia de Produção',
  'Estética e Cosmética',
  'Farmácia',
  'Fotografia',
  'Gastronomia',
  'Gestão Comercial',
  'Gestão da Tecnologia da Informação',
  'Gestão de Hospitalidade',
  'Gestão de Recursos Humanos',
  'Gestão Financeira',
  'Graduação em Educação Física',
  'Hotelaria',
  'Jogos Digitais',
  'Logística',
  'Marketing',
  'Nutrição',
  'Processos Gerenciais',
  'Produção Multimídia',
  'Publicidade e Propaganda',
  'Radiologia',
  'Redes de Computadores',
  'Sistemas de Informação',
  'Sistemas para Internet'
]